### PR TITLE
Refine xref reconstruction (fixes #1335)

### LINKED ISSUE #1335: qpdf fails to repair this pdf
https://dl.acm.org/doi/pdf/10.1109/SC41406.2024.00008

PDF is behind a paywall but there's a workaround for that:

Start private browsing session, go to google, input exactly the address https://dl.acm.org/doi/pdf/10.1109/SC41406.2024.00008  and click on the first link. There is a red PDF button that gives you the PDF file.

```
$ sha256sum SC41406.2024.00008.pdf 
6690cf80b47f385a16b34e41a4d6566a86681eb1b920ba37d3a9a2fd90c82565  SC41406.2024.00008.pdf
```

Firefox, Chrome and Adobe Reader are able to recover from it, but qpdf is not able to repair it.

```
$ qpdf SC4.pdf SC4_repaired.pdf
WARNING: SC4.pdf: file is damaged
WARNING: SC4.pdf (offset 216): xref not found
WARNING: SC4.pdf: Attempting to reconstruct cross-reference table
WARNING: SC4.pdf: reported number of objects (99) is not one plus the highest object number (250)
qpdf: SC4.pdf: unable to find /Root dictionary
```
qpdf did not even write the output file SC4_repaired.pdf

### PR DESCRIPTION
**Pull request by m-holger**
When recovering XRef streams, start with the stream with the largest /Size rather than the largest offset.

Also, if reconstruction fails to find a trailer with a valid /Root entry search for a root object.

### CODE REVIEW

**Comment by m-holger** [comment]
Reminder to self: reopen #1335 after merging.

File: libqpdf/QPDF.cc [hunk 1]
```diff
@@ -633,13 +635,35 @@ QPDF::reconstruct_xref(QPDFExc& e)
...
-                    "", 0, "error decoding candidate xref stream while recovering damaged file");
+                warn(damagedPDF(
+                    "", 0, "error decoding candidate xref stream while recovering damaged file"));
             }
             QTC::TC("qpdf", "QPDF recover xref stream");
         }
     }
 
+    if (!m->trailer || (!m->parsed && !m->trailer.getKey("/Root").isDictionary())) {
+        // Try find a Root dictionary. As a quick fix try the one with the highest object id.
```
Comment (jberkenbilt) [inline libqpdf/QPDF.cc:646]: Try _to_ find (missing word)

File: qpdf/qtest/qpdf/bad16-recover.out [hunk 2]
```diff
@@ -11,4 +11,10 @@ WARNING: bad16.pdf (trailer, offset 756): unexpected dictionary close token
 WARNING: bad16.pdf (trailer, offset 759): unknown token while reading object; treating as string
 WARNING: bad16.pdf (trailer, offset 779): parse error while reading object
 WARNING: bad16.pdf (trailer, offset 779): unexpected EOF
-bad16.pdf: unable to find trailer dictionary while recovering damaged file
+WARNING: bad16.pdf: unable to find trailer dictionary while recovering damaged file
```
Comment (jberkenbilt) [inline qpdf/qtest/qpdf/bad16-recover.out:14]: This is great.

**Review by jberkenbilt — APPROVED** [review]
I like this change. Looks great other than the missing word in the comment. I must be rubbing off on you.
